### ISSUE TITLE
CookieSessionUserHandlerの認証エラーについて

### ISSUE THREAD

**Issue by sniper1107** [tsukumijima/tweepy-authlib#8]
こんにちは
version 1.5.4に更新してくださったとのことで、
バージョンアップ後にサンプルコードexample_json.pyを実行してみましたが、
CookieSessionUserHandler実行後、下記エラーが発生します。
「Failed to authenticate with password (Code: 366, Message: flow name LoginFlow is currently not accessible)」
事前のログアウトやアカウント変更も試みましたが、改善しませんでした。
ただエラー発生時にXから「新しい端末からログインがありました」と通知は出るのでログイン自体はできているように思います。
解決方法などご教示いただけないでしょうか？

Pythonのバージョンは3.11.9です。

**Comment by tsukumijima** [comment]
@sniper1107 
ご連絡ありがとうございます。
手元でも試してみましたが、おそらく Twitter 側の仕様変更により動作しなくなっているようです。修正を検討します。

**Comment by tsukumijima** [comment]
@sniper1107 直ったようで何よりです！
